server:
  port: 31001
spring:
  application:
    name: cms
  data:
    mongodb:
      uri:  mongodb://root:root@192.168.2.101:27017/xc_cms
      database: xc_cms
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0
